export const cards = [
  { id: 1, name: 'Alliant Cashback Visa Signature Card' },
  { id: 2, name: 'Amazon Business American Express Card' },
  { id: 3, name: 'Amazon Business Prime American Express Card' },
  { id: 4, name: 'American Express Blue Business Cash Card' },
  { id: 5, name: 'American Express Business Gold Card' },
  { id: 6, name: 'American Express Cash Magnet Card' },
  { id: 7, name: 'American Express Gold Card' },
  { id: 8, name: 'Amex EveryDay Preferred Credit Card' },
  { id: 9, name: 'Blue Cash Everyday Card from American Express' },
  { id: 10, name: 'Blue Cash Preferred Card from American Express' },
  { id: 11, name: 'Blue from American Express Card' },
  { id: 12, name: 'Business Green Rewards Card from American Express' },
  { id: 13, name: 'Delta SkyMiles Blue American Express Card' },
  { id: 14, name: 'Delta SkyMiles Gold American Express Card' },
  { id: 15, name: 'Delta SkyMiles Gold Business American Express Card' },
  { id: 16, name: 'Delta SkyMiles Platinum American Express Card' },
  { id: 17, name: 'Delta SkyMiles Platinum Business American Express Card' },
  { id: 18, name: 'Delta SkyMiles Reserve American Express Card' },
  { id: 19, name: 'Delta SkyMiles Reserve Business American Express Card' },
  { id: 20, name: 'Hilton Honors American Express Aspire Card' },
  { id: 21, name: 'Hilton Honors American Express Card' },
  { id: 22, name: 'Hilton Honors American Express Surpass Card' },
  { id: 23, name: "Macy's American Express Card" },
  { id: 24, name: 'Marriott Bonvoy Brilliant American Express Card' },
  { id: 25, name: 'Marriott Bonvoy Business American Express Card' },
  { id: 26, name: 'The Blue Business Plus Credit Card from American Express' },
  { id: 27, name: 'The Business Platinum Card from American Express' },
  { id: 28, name: 'The Hilton Honors American Express Business Card' },
  { id: 29, name: 'The Platinum Card from American Express' },
  { id: 30, name: 'The Plum Card from American Express' },
  { id: 31, name: 'Applied Bank Secured Visa Gold Preferred Credit Card' },
  { id: 32, name: 'Applied Bank Unsecured Classic Visa Card' },
  { id: 33, name: 'Alaska Airlines Business Credit Card' },
  { id: 34, name: 'Alaska Airlines Visa Signature credit card' },
  { id: 35, name: 'BankAmericard credit card' },
  { id: 36, name: 'BankAmericard Secured Credit Card' },
  { id: 37, name: 'Bank of America Allegiant World Mastercard Credit Card' },
  {
    id: 38,
    name: 'Bank of America Business Advantage Cash Rewards credit card',
  },
  {
    id: 39,
    name:
      'Bank of America Business Advantage Travel Rewards World Mastercard credit card',
  },
  { id: 40, name: 'Bank of America Cash Rewards Credit Card for Students' },
  {
    id: 41,
    name: 'Bank of America Celebrity Cruises Visa Signature Credit Card',
  },
  { id: 42, name: 'Bank of America Customized Cash Rewards credit card' },
  { id: 43, name: 'Bank of America Norwegian Cruise Line World Mastercard' },
  { id: 44, name: 'Bank of America Platinum Plus Mastercard Business card' },
  { id: 45, name: 'Bank of America Premium Rewards credit card' },
  {
    id: 46,
    name: 'Bank of America Royal Caribbean Visa Signature Credit Card',
  },
  { id: 47, name: 'Bank of America Sandals Visa Signature Credit Card' },
  { id: 48, name: 'Bank of America Spirit Airlines World Mastercard' },
  { id: 49, name: 'Bank of America Travel Rewards credit card' },
  { id: 50, name: 'Bank of America Travel Rewards Credit Card for Students' },
  { id: 51, name: 'Bank of America U.S. Pride Credit Card' },
  { id: 52, name: 'Virgin Atlantic World Elite Mastercard' },
  { id: 53, name: 'AAdvantage Aviator Red World Elite Mastercard' },
  { id: 54, name: 'Bluegreen Rewards Mastercard' },
  { id: 55, name: 'Carnival World Mastercard' },
  { id: 56, name: 'Choice Privileges Visa Signature Card' },
  { id: 57, name: 'Diamond Resorts World Mastercard' },
  { id: 58, name: 'Frontier Airlines World Mastercard' },
  { id: 59, name: 'Hawaiian Airlines Business Mastercard' },
  { id: 60, name: 'Holland America Line Rewards Visa Card' },
  { id: 61, name: 'JetBlue Business Card' },
  { id: 62, name: 'JetBlue Plus Card' },
  { id: 63, name: 'Miles & More World Elite Mastercard' },
  { id: 64, name: 'Priceline Rewards Visa Card' },
  { id: 65, name: 'Princess Cruises Rewards Visa Card' },
  { id: 66, name: 'Wyndham Rewards Earner Card' },
  { id: 67, name: 'BB&T Bright Card' },
  { id: 68, name: 'BB&T Spectrum Cash Rewards credit card' },
  { id: 69, name: 'Brex 30 Card' },
  { id: 70, name: 'OpenSky Secured Visa Credit Card' },
  { id: 71, name: 'BuyPower Business Card' },
  { id: 72, name: 'BuyPower Card' },
  { id: 73, name: 'Capital One Platinum Credit Card' },
  { id: 74, name: 'Capital One Quicksilver Cash Rewards Credit Card' },
  { id: 75, name: 'Capital One QuicksilverOne Cash Rewards Credit Card' },
  { id: 76, name: 'Capital One Savor Cash Rewards Credit Card' },
  { id: 77, name: 'Capital One SavorOne Cash Rewards Credit Card' },
  { id: 78, name: 'Capital One Spark Cash for Business' },
  { id: 79, name: 'Capital One Spark Cash Select for Business' },
  { id: 80, name: 'Capital One Spark Classic for Business' },
  { id: 81, name: 'Capital One Spark Miles for Business' },
  { id: 82, name: 'Capital One Spark Miles Select for Business' },
  { id: 83, name: 'Capital One VentureOne Rewards Credit Card' },
  { id: 84, name: 'Capital One Venture Rewards Credit Card' },
  { id: 85, name: 'Capital One Walmart Rewards Mastercard' },
  { id: 86, name: 'Journey Student Rewards from Capital One' },
  { id: 87, name: 'Secured Mastercard from Capital One' },
  { id: 88, name: 'Amazon Rewards Visa Signature Card' },
  { id: 89, name: 'British Airways Visa Signature Card' },
  { id: 90, name: 'Chase Freedom Flex' },
  { id: 91, name: 'Chase Freedom Student credit card' },
  { id: 92, name: 'Chase Freedom Unlimited' },
  { id: 93, name: 'Chase Sapphire Preferred Card' },
  { id: 94, name: 'Chase Sapphire Reserve' },
  { id: 95, name: 'Disney Premier Visa Card' },
  { id: 96, name: 'IHG Rewards Club Premier Credit Card' },
  { id: 97, name: 'Ink Business Cash Credit Card' },
  { id: 98, name: 'Ink Business Preferred Credit Card' },
  { id: 99, name: 'Ink Business Unlimited Credit Card' },
  { id: 100, name: 'Marriott Bonvoy Bold Credit Card' },
  { id: 101, name: 'Marriott Bonvoy Boundless Credit Card' },
  { id: 102, name: 'New United Quest Card' },
  {
    id: 103,
    name: 'Southwest Rapid Rewards Performance Business Credit Card',
  },
  { id: 104, name: 'Southwest Rapid Rewards Plus Credit Card' },
  { id: 105, name: 'Southwest Rapid Rewards Premier Business Credit Card' },
  { id: 106, name: 'Southwest Rapid Rewards Premier Credit Card' },
  { id: 107, name: 'Southwest Rapid Rewards Priority Credit Card' },
  { id: 108, name: 'Starbucks Rewards Visa Card' },
  { id: 109, name: 'United Business Card' },
  { id: 110, name: 'United Club Infinite Card' },
  { id: 111, name: 'United Explorer Card' },
  { id: 112, name: 'United Gateway Card' },
  { id: 113, name: 'American Airlines AAdvantage MileUp Card' },
  { id: 114, name: 'AT&T Access Card from Citi' },
  { id: 115, name: 'Citi / AAdvantage Executive World Elite Mastercard' },
  {
    id: 116,
    name: 'Citi / AAdvantage Platinum Select World Elite Mastercard',
  },
  { id: 117, name: 'CitiBusiness / AAdvantage Platinum Select Mastercard' },
  { id: 118, name: 'Citi Diamond Preferred Card' },
  { id: 119, name: 'Citi Double Cash Card - 18 month BT offer' },
  { id: 120, name: 'Citi Premier Card' },
  { id: 121, name: 'Citi Prestige Credit Card' },
  { id: 122, name: 'Citi Rewards+ Card' },
  { id: 123, name: 'Citi Secured Mastercard' },
  { id: 124, name: 'Citi Simplicity Card - No Late Fees Ever' },
  { id: 125, name: 'My Best Buy Visa Card' },
  { id: 126, name: 'Citizens Bank Cash Back Plus World Mastercard' },
  { id: 127, name: 'Lands’ End Visa Credit Card' },
  { id: 128, name: 'Commerce Bank Secured Visa Credit Card' },
  { id: 129, name: 'Commerce Bank VOILÀ Hotel Rewards Visa Signature' },
  { id: 130, name: 'Special Connections credit card' },
  { id: 131, name: 'Credit One Bank American Express Card' },
  { id: 132, name: 'Credit One Bank Platinum Rewards Visa' },
  {
    id: 133,
    name: 'Credit One Bank Platinum Rewards Visa with No Annual Fee',
  },
  { id: 134, name: 'Credit One Bank Unsecured Visa with Cash Back Rewards' },
  { id: 135, name: 'Credit One Bank Visa Cash Back Rewards' },
  { id: 136, name: 'NASCAR Credit Card from Credit One Bank' },
  { id: 137, name: 'Deserve EDU Mastercard for Students' },
  { id: 138, name: 'Discover it Business Card' },
  { id: 139, name: 'Discover it Cash Back' },
  { id: 140, name: 'Discover it chrome' },
  { id: 141, name: 'Discover it Miles' },
  { id: 142, name: 'Discover it Secured Credit Card' },
  { id: 143, name: 'Discover it Student Cash Back' },
  { id: 144, name: 'Discover it Student chrome' },
  { id: 145, name: 'NHL Discover it' },
  { id: 146, name: 'Fifth Third Secured Card' },
  { id: 147, name: 'Truly Simple Credit Card' },
  { id: 148, name: 'Best Western Rewards Premium Mastercard' },
  { id: 149, name: 'First National Bank Secured Visa Card' },
  { id: 150, name: 'Sun Country Airlines Visa Signature Card' },
  {
    id: 151,
    name: 'First Progress Platinum Prestige Mastercard Secured Credit Card',
  },
  { id: 152, name: 'Destiny Mastercard' },
  { id: 153, name: 'Indigo Platinum Mastercard' },
  { id: 154, name: 'Milestone Gold Mastercard' },
  { id: 155, name: 'Apple Card' },
  { id: 156, name: 'HSBC Advance Mastercard credit card' },
  { id: 157, name: 'HSBC Cash Rewards Mastercard credit card' },
  { id: 158, name: 'HSBC Gold Mastercard credit card' },
  { id: 159, name: 'HSBC Premier World Mastercard credit card' },
  { id: 160, name: 'Mastercard Black Card' },
  { id: 161, name: 'Mastercard Gold Card' },
  { id: 162, name: 'Mastercard Titanium Card' },
  { id: 163, name: 'M&T Business Credit Card' },
  { id: 164, name: 'M&T Business Rewards Credit Card' },
  { id: 165, name: 'M&T Visa Credit Card' },
  { id: 166, name: 'M&T Visa Credit Card with Rewards' },
  { id: 167, name: 'M&T Visa Signature Credit Card' },
  { id: 168, name: 'Navy Federal nRewards Secured Credit Card' },
  { id: 169, name: 'PNC BusinessOptions Visa Signature Credit Card' },
  { id: 170, name: 'PNC Cash Rewards Visa Credit Card' },
  { id: 171, name: 'PNC Core Visa Credit Card' },
  { id: 172, name: 'PNC points Visa Business Credit Card' },
  { id: 173, name: 'PNC points Visa Credit Card' },
  { id: 174, name: 'PNC Premier Traveler Visa Signature Credit Card' },
  { id: 175, name: 'PNC Travel Rewards Visa Business Credit Card' },
  { id: 176, name: 'PNC Visa Business Credit Card' },
  { id: 177, name: 'Simmons Rewards Visa Signature' },
  { id: 178, name: 'Simmons Visa' },
  { id: 179, name: 'SDFCU Savings Secured Visa Platinum Card' },
  { id: 180, name: 'SunTrust Business Cash Rewards Credit Card' },
  { id: 181, name: 'SunTrust Cash Rewards Credit Card' },
  { id: 182, name: 'SunTrust Prime Rewards Credit Card' },
  { id: 183, name: 'SunTrust Secured Credit Card with Cash Rewards' },
  { id: 184, name: 'SunTrust Travel Rewards Credit Card' },
  { id: 185, name: 'AEO Connected credit card' },
  { id: 186, name: 'BP Visa Credit Card' },
  { id: 187, name: 'Gap Inc. Visa Card' },
  { id: 188, name: 'Lowe’s Advantage Card' },
  { id: 189, name: 'Techron Advantage Visa Card' },
  { id: 190, name: 'Verizon Visa Card' },
  { id: 191, name: 'Target REDcard' },
  { id: 192, name: 'TD Ameritrade Client Rewards Card' },
  { id: 193, name: 'TD Business Solutions Credit Card' },
  { id: 194, name: 'TD Cash Credit Card' },
  { id: 195, name: 'TD First Class Visa Signature Credit Card' },
  { id: 196, name: 'Fit Mastercard Credit Card' },
  { id: 197, name: 'Total Visa Unsecured Credit Card' },
  { id: 198, name: 'Upgrade Visa Card with Cash Rewards' },
  { id: 199, name: 'USAA Cashback Rewards Plus American Express Card' },
  { id: 200, name: 'USAA Preferred Cash Rewards Visa Signature Card' },
  { id: 201, name: 'USAA Rate Advantage Visa Platinum Card' },
  { id: 202, name: 'USAA Rewards American Express Card' },
  { id: 203, name: 'USAA Rewards Visa Signature Card' },
  { id: 204, name: 'LATAM Visa Card' },
  { id: 205, name: 'LATAM Visa Secured Card' },
  { id: 206, name: 'LATAM Visa Signature Card' },
  { id: 207, name: 'Radisson Rewards Premier Visa Signature Card' },
  { id: 208, name: 'Radisson Rewards Visa Card' },
  { id: 209, name: 'REI Co-op Mastercard' },
  { id: 210, name: 'SkyBlue SKYPASS Visa Card' },
  { id: 211, name: 'SKYPASS Visa Business Card' },
  { id: 212, name: 'SKYPASS Visa Signature Card' },
  { id: 213, name: 'U.S. Bank Altitude Connect Visa Signature Card' },
  { id: 214, name: 'U.S. Bank Altitude Go Visa Signature Card' },
  { id: 215, name: 'U.S. Bank Business Cash Rewards World Elite MasterCard' },
  { id: 216, name: 'U.S. Bank Business Leverage Visa Signature Card' },
  { id: 217, name: 'U.S. Bank Business Platinum Card' },
  { id: 218, name: 'U.S. Bank Cash+ Visa Signature Card' },
  { id: 219, name: 'U.S. Bank FlexPerks Gold American Express Card' },
  { id: 220, name: 'U.S. Bank Secured Visa Card' },
  { id: 221, name: 'U.S. Bank Visa Platinum Card' },
  { id: 222, name: 'Petal 1 "No Annual Fee" Visa Credit Card' },
  { id: 223, name: 'Petal 2 "Cash Back, No Fees" Visa Credit Card' },
  { id: 224, name: 'Hotels.com Rewards Visa Credit Card' },
  { id: 225, name: 'Wells Fargo Business Elite Card' },
  { id: 226, name: 'Wells Fargo Business Platinum Credit Card' },
  { id: 227, name: 'Wells Fargo Business Secured Credit Card' },
  { id: 228, name: 'Wells Fargo Cash Back College Card' },
  { id: 229, name: 'Wells Fargo Cash Wise Visa card' },
  { id: 230, name: 'Wells Fargo Platinum card' },
  { id: 231, name: 'Wells Fargo Propel American Express card' },
  { id: 232, name: 'Wells Fargo Rewards Card' },
  { id: 233, name: 'Wells Fargo Visa Signature Card' },
]
