FROM node:latest

# create app directory
WORKDIR /app

COPY server/package*.json ./

RUN npm install

COPY server/ .

RUN npm run build

ARG DATABASE_URL
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG COOKIE_SECRET
ARG SERVER_DOMAIN
ARG CLIENT_DOMAIN

ENV DATABASE_URL=$DATABASE_URL
RUN echo "HERE"
RUN echo $DATABASE_URL

ENV GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
ENV COOKIE_SECRET=$COOKIE_SECRET
ENV SERVER_DOMAIN=$SERVER_DOMAIN
ENV CLIENT_DOMAIN=$CLIENT_DOMAIN

RUN npm run db

RUN npm run db-generate

EXPOSE 3000
CMD [ "npm", "start"]


