-- CreateEnum
CREATE TYPE "Bank" AS ENUM ('CHASE_BANK', 'BANK_OF_AMERICA', 'WELLS_FARGO', 'US_BANK', 'BBVA_COMPASS', 'CAPITAL_ONE_BANK', 'BANK_OF_THE_WEST', 'SANTANDER_CONSUMER_BANK', 'CITI_BANK', 'HUNTINGTON_BANK', 'M_AND_T_BANK', 'WOODFOREST_NATIONAL_BANK', 'CITIZENS_BANK', 'FIFTH_THIRD_BANK', 'KEY_BANK', 'TD_BANK', 'SUN_TRUST_BANK', 'REGIONS_BANK', 'PNC_BANK', 'BB_AND_T_BANK', 'FIRST_NATIONAL_BANK', 'BMO_HARRIS_BANK', 'FIRST_CITIZENS_BANK', 'COMERICA_BANK', 'PEOPLES_UNITED_BANK', 'UMPQUA_BANK', 'BANK_OF_THE_OZARKS', 'HSBC', 'MUFG_UNION_BANK', 'ARVEST_BANK', 'CHEMICAL_BANK', 'TCF_BANK', 'SYNOVUS_BANK', 'BANCORP_SOUTH_BANK', 'WASHINGTON_FEDERAL', 'ASSICIATED_BANK', 'IBERIABANK', 'VALLEY_NATIONAL_BANK', 'WHITNEY_BANK', 'TRUST_MARK_NATIONAL_BANK', 'GREAT_WESTERN_BANK', 'COLUMBIA_STATE_BANK', 'CENTENNIAL_BANK', 'OLD_NATIONAL_BANK', 'SOUTH_STATE_BANK', 'FIRST_TENNESSEE_BANK', 'NBT_BANK', 'RENASANT_BANK', 'BANNER_BANK', 'WEBSTER_BANK', 'SIMMONS_BANK', 'UNITED_BANK', 'FROST_BANK', 'WESBANCO_BANK', 'COMMERCE_BANK', 'INVESTORS_BANK', 'TRUSTCO_BANK', 'FIRST_COMMONWEALTH_BANK', 'STERLING_NATIONAL_BANK', 'CARTER_BANK_AND_TRUST', 'FIRST_MIDWEST_BANK', 'FIRST_BANK', 'PARK_NATIONAL_BANK', 'PINNACLE_BANK', 'GLACIER_BANK', 'FULTON_BANK', 'RABOBANK', 'ZIONS_BANK', 'FIRST_MERCHANTS_BANK', 'EAST_WEST_BANK', 'FIRST_INTERSTATE_BANK', 'UNION_BANK_AND_TRUST', 'GREAT_SOUTHERN_BANK', 'FLAGSTER_BANK');

-- CreateTable
CREATE TABLE "Card" (
    "id" SERIAL NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "creditLimit" DECIMAL(15,2),
    "totalSpend" DECIMAL(15,2),
    "outstandingBalance" DECIMAL(15,2),
    "minimumSpendingRequirement" DECIMAL(15,2),
    "annualFee" DECIMAL(15,2),
    "annualFeeDate" TIMESTAMP(3),
    "signupBonusDueDate" TIMESTAMP(3),
    "applicationDate" TIMESTAMP(3),
    "approvalDate" TIMESTAMP(3),
    "lastChargeDate" TIMESTAMP(3),
    "bank" "Bank",
    "published" BOOLEAN DEFAULT false,
    "ownerId" INTEGER NOT NULL,

    PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "User" (
    "id" SERIAL NOT NULL,
    "email" TEXT NOT NULL,
    "name" TEXT,

    PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "User.email_unique" ON "User"("email");

-- AddForeignKey
ALTER TABLE "Card" ADD FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
